// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Тип инициализации сервисов Сбербанка */
enum class SberPayApiEnv(val raw: Int) {
  /**
   * Продуктовый режим.
   *
   * Для авторизации пользователя происходит редирект в приложение Сбербанка.
   */
  PROD(0),
  /**
   * Режим песочницы.
   *
   * Позволяет протестировать оплату как в [prod], но с тестовыми данными.
   */
  SANDBOX_REAL_BANK_APP(1),
  /**
   * Режим песочницы без перехода в банк.
   *
   * При авторизации пользователя не осуществляется переход в приложение
   * Сбербанка.
   */
  SANDBOX_WITHOUT_BANK_APP(2);

  companion object {
    fun ofRaw(raw: Int): SberPayApiEnv? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Статусы оплаты */
enum class SberPayApiPaymentStatus(val raw: Int) {
  /** Успешный результат */
  SUCCESS(0),
  /** Необходимо проверить статус оплаты */
  PROCESSING(1),
  /** Пользователь отменил оплату */
  CANCEL(2),
  /** Неизвестный тип */
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): SberPayApiPaymentStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Тип оплаты (сценарий) */
enum class PaymentMethod(val raw: Int) {
  INVOICE(0),
  AUTO_PAYMENT(1);

  companion object {
    fun ofRaw(raw: Int): PaymentMethod? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Конфигурация инициализации
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class InitConfig (
  /** Ключ, выдаваемый по договору, либо создаваемый в личном кабинете */
  val apiKey: String,
  /** Логин, выдаваемый по договору, либо создаваемый в личном кабинете */
  val merchantLogin: String,
  /** Среда запуска */
  val env: SberPayApiEnv,
  /** Использование функционала оплаты частями */
  val enableBnpl: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InitConfig {
      val apiKey = pigeonVar_list[0] as String
      val merchantLogin = pigeonVar_list[1] as String
      val env = pigeonVar_list[2] as SberPayApiEnv
      val enableBnpl = pigeonVar_list[3] as Boolean?
      return InitConfig(apiKey, merchantLogin, env, enableBnpl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apiKey,
      merchantLogin,
      env,
      enableBnpl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is InitConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Конфигурация оплаты
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PaymentRequest (
  /** Ключ, выдаваемый по договору, либо создаваемый в личном кабинете */
  val apiKey: String? = null,
  /** Логин, выдаваемый по договору, либо создаваемый в личном кабинете */
  val merchantLogin: String? = null,
  /** Уникальный идентификатор заказа, сгенерированный Банком */
  val bankInvoiceId: String,
  /** Диплинк для перехода обратно в приложение после открытия Сбербанка */
  val redirectUri: String,
  /** Номер заказа */
  val orderNumber: String,
  /** Метод оплаты */
  val paymentMethod: PaymentMethod
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PaymentRequest {
      val apiKey = pigeonVar_list[0] as String?
      val merchantLogin = pigeonVar_list[1] as String?
      val bankInvoiceId = pigeonVar_list[2] as String
      val redirectUri = pigeonVar_list[3] as String
      val orderNumber = pigeonVar_list[4] as String
      val paymentMethod = pigeonVar_list[5] as PaymentMethod
      return PaymentRequest(apiKey, merchantLogin, bankInvoiceId, redirectUri, orderNumber, paymentMethod)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apiKey,
      merchantLogin,
      bankInvoiceId,
      redirectUri,
      orderNumber,
      paymentMethod,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PaymentRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SberPayApiEnv.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SberPayApiPaymentStatus.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PaymentMethod.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InitConfig.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PaymentRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SberPayApiEnv -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is SberPayApiPaymentStatus -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is PaymentMethod -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is InitConfig -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PaymentRequest -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SberPayApi {
  fun initSberPay(config: InitConfig, callback: (Result<Boolean>) -> Unit)
  fun isReadyForSPaySdk(callback: (Result<Boolean>) -> Unit)
  fun pay(request: PaymentRequest, callback: (Result<SberPayApiPaymentStatus>) -> Unit)

  companion object {
    /** The codec used by SberPayApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `SberPayApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SberPayApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sber_pay_android.SberPayApi.initSberPay$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as InitConfig
            api.initSberPay(configArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sber_pay_android.SberPayApi.isReadyForSPaySdk$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isReadyForSPaySdk{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sber_pay_android.SberPayApi.pay$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PaymentRequest
            api.pay(requestArg) { result: Result<SberPayApiPaymentStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
